# Generated by Django 3.0.7 on 2020-07-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='leftbotx',
            new_name='lefttopx',
        ),
        migrations.RenameField(
            model_name='box',
            old_name='leftboty',
            new_name='lefttopy',
        ),
        migrations.RenameField(
            model_name='box',
            old_name='righttopx',
            new_name='rightbotx',
        ),
        migrations.RenameField(
            model_name='box',
            old_name='righttopy',
            new_name='rightboty',
        ),
        migrations.AlterField(
            model_name='imageusertagbox',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
