# Generated by Django 3.0.7 on 2020-07-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20200701_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(through='images.ImageUserTagBox', to='images.Tag'),
        ),
    ]
